language: ruby
sudo: false

notifications:
  email: false

rvm:
  - 2.3.4

matrix:
  include:
    - rvm: 2.3.4
      env: "RAILS_VERSION=4.2.8"
    - rvm: 2.3.4
      env: "RAILS_VERSION=5.0.3"

before_install:
  - gem update --system
  - gem install bundler

env:
 - "RAILS_VERSION=5.0.3"

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jdk: oraclejdk8
